insert into profiles(email, phone_number, residence) values ('email@gmail.com', '0623890342', 'Amsterdam');
insert into users(username, password, profile_id) values ('testadmin', '$2a$12$GcbQlWzYl6xf1DbXTipSzOe2qrDKLj.TRxgDIDQoizHJ8bJoBLjlW', 1);
insert into profiles(email, phone_number, residence) values ('example@gmail.com', '0677235712', 'Nijmegen');
insert into users(username, password, profile_id) values ('testuser', '$2a$12$GcbQlWzYl6xf1DbXTipSzOe2qrDKLj.TRxgDIDQoizHJ8bJoBLjlW', 2);
insert into roles(role) values ('ROLE_USER'), ('ROLE_ADMIN');
insert into users_roles(user_id, role) values ('1', 'ROLE_USER');
insert into users_roles(user_id, role) values ('1', 'ROLE_ADMIN');
insert into users_roles(user_id, role) values ('2', 'ROLE_USER');
insert into categories(parent_id, title) values (null, 'Voertuigen');
insert into categories(parent_id, title) values (1, 'Auto''s en motoren');
insert into categories(parent_id, title) values (1, 'Andere voertuigen');
insert into categories(parent_id, title) values (1, 'Boten');
insert into categories(parent_id, title) values (null, 'Verzamelobjecten');
insert into categories(parent_id, title) values (5, 'Munten');
insert into categories(parent_id, title) values (5, 'Postzegels');
insert into categories(parent_id, title) values (5, 'Antiek');
insert into categories(parent_id, title) values (5, 'Kunst');
insert into categories(parent_id, title) values (null, 'Kleding en sport');
insert into categories(parent_id, title) values (10, 'Mannen kleding');
insert into categories(parent_id, title) values (10, 'Vrouwen kleding');
insert into categories(parent_id, title) values (10, 'Kinder kleding');
insert into categories(parent_id, title) values (10, 'Baby kleding');
insert into categories(parent_id, title) values (10, 'Accessoires');
insert into categories(parent_id, title) values (10, 'Juwelen');
insert into categories(parent_id, title) values (10, 'Reisbagage');
insert into categories(parent_id, title) values (10, 'Sportuitrusting');
insert into categories(parent_id, title) values (10, 'Visuitrusting');
insert into categories(parent_id, title) values (null, 'Electronica');
insert into categories(parent_id, title) values (20, 'Computers');
insert into categories(parent_id, title) values (20, 'Tablets');
insert into categories(parent_id, title) values (20, 'Laptops');
insert into categories(parent_id, title) values (20, 'Telefoons');
insert into categories(parent_id, title) values (20, 'Camera''s');
insert into categories(parent_id, title) values (20, 'Tv''s');
insert into categories(parent_id, title) values (20, 'Audioapparatuur');
insert into categories(parent_id, title) values (20, 'Koptelefoons');
insert into categories(parent_id, title) values (20, 'Vriezers');
insert into categories(parent_id, title) values (20, 'Koelkasten');
insert into categories(parent_id, title) values (null, 'Huis en tuin');
insert into categories(parent_id, title) values (31, 'Tuinapparatuur');
insert into categories(parent_id, title) values (31, 'Tuinmeubels');
insert into categories(parent_id, title) values (31, 'Binnenmeubels');
insert into categories(parent_id, title) values (31, 'Slaapproducten');
insert into categories(parent_id, title) values (31, 'Stofzuigers');
insert into categories(parent_id, title) values (31, 'Keukengerei');
insert into categories(parent_id, title) values (31, 'Lampen');
insert into categories(parent_id, title) values (null, 'Eigen tijd');
insert into categories(parent_id, title) values (39, 'Boeken');
insert into categories(parent_id, title) values (39, 'Muziekinstrumenten');
insert into categories(parent_id, title) values (39, 'CD''s');
insert into categories(parent_id, title) values (39, 'Vinyl');
insert into categories(parent_id, title) values (39, 'Games');
insert into categories(parent_id, title) values (39, 'DVD''s');
insert into categories(parent_id, title) values (39, 'blu-ray');
insert into categories(parent_id, title) values (null, 'Gezondheidsproducten');
insert into categories(parent_id, title) values (47, 'Parfum');
insert into categories(parent_id, title) values (47, 'Makeup');
insert into categories(parent_id, title) values (47, 'Huidverzorging');
insert into categories(parent_id, title) values (47, 'Haarstijlproducten');
insert into categories(parent_id, title) values (47, 'Scheerproducten');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'BMW 2e serie', '5 zits met ruime achterbank en veel baggageruimte', 20500.0, 'bmw.png', 'Gekocht in 2017', 'goed', 'checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Mooie antieke kast', 'Leuke kast met veel laatjes', 1200.0, 'antiekekast.png', 'Al lang in bezit', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Verouderde bagagetas', 'Makkelijk te gebruiken voor stedentrips', 20.0, 'bagagetas.png', '30 bij 20 bij 25', 'slecht', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Leuke bank', 'Wij willen een nieuwe', 600.0, 'bank.png', '2 en een halve meter lang', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Nieuwe blender', 'Nog niet lang in gebruik', 100.0, 'blender.png', 'De bovenkant vliegt er steeds vanaf', 'goed', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Onze oude boot', 'Weten niet wat het merk is', 5000.0, 'boot.png', '4 meter lang', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Feestjeskoelkast', 'passen wel 4 kratten bier in', 300.0, 'buitenkoelkast.png', '2 meter hoog, 1 krat breed', 'nieuw', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'lekker hoor', 'Heb de helft al op', 20.0, 'chocolademunten.png', 'En nu de rest ook', 'prima',null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Super leuke oude laptop', 'Een echt colletor''s item', 400.0, 'compaqlaptop.png', 'Van het merk Compaq ofzo', 'slecht', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Mooie dacia', 'Al 10 jaar in bezit, maar het is tijd voor iets nieuws', 6000.0, 'dacia.png', '5 zits met grote, 5 deurs', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Trendy blender', 'Weer super hip', 30.0, 'ElectricBlender.png', '30cm hoog', 'goed', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Designer emmer', 'Ik weet eigenlijk niet wat het is', 200.0, 'emmer.png', 'uuuuuuh', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Oude koelkast', 'Ligt nog helemaal vol met spul', 50.0, 'koelkast.png', 'spul krijg je er niet bij', 'zeer slecht', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Vintage lamp', 'Gisteren gekocht', 80.0, 'lamp.png', 'Grijs op grijs op grijs', 'slecht',null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Prachtige MG', 'Opgeknapt door de vorige eigenaar', 22500.0, 'mg.png', 'bouwjaar 1966', 'prima', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Zelfgebreide trui van oma', '', 20.0, 'oudetrui.png', '', 'slecht','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Stapel random boeken', 'Zitten wat oude klassiekers tussen', 85.0, 'stapelboeken.png', '6 in totaal', 'goed', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Henry my beloved', 'henry', 50.0, 'stofzuiger.png', 'henry', 'prima','checked');
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (1, 'Oude flatscreen tv', 'Het paard is niet inbegrepen', 130.0, 'tv.png', '55 inch', 'zeer slecht', null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Foto model plaat', 'Volledige zwart', 20.0, 'vinyl.png', 'staat niks op', 'nieuw',null);
insert into advertisements(user_id, title, description, price, image, details, state, has_to_go) values (2, 'Coole zwarte jas', 'kan nog veel jaren mee', 70.0, 'zwartejas.png', 'size L', 'prima','checked');
insert into advertisements_categories(advertisement_id, category_id) values (1, 2);
insert into advertisements_categories(advertisement_id, category_id) values (2, 8);
insert into advertisements_categories(advertisement_id, category_id) values (3, 17);
insert into advertisements_categories(advertisement_id, category_id) values (4, 34);
insert into advertisements_categories(advertisement_id, category_id) values (5, 37);
insert into advertisements_categories(advertisement_id, category_id) values (6, 4);
insert into advertisements_categories(advertisement_id, category_id) values (7, 30);
insert into advertisements_categories(advertisement_id, category_id) values (8, 6);
insert into advertisements_categories(advertisement_id, category_id) values (9, 23);
insert into advertisements_categories(advertisement_id, category_id) values (10, 2);
insert into advertisements_categories(advertisement_id, category_id) values (11, 37);
insert into advertisements_categories(advertisement_id, category_id) values (12, 8);
insert into advertisements_categories(advertisement_id, category_id) values (13, 30);
insert into advertisements_categories(advertisement_id, category_id) values (14, 38);
insert into advertisements_categories(advertisement_id, category_id) values (15, 2);
insert into advertisements_categories(advertisement_id, category_id) values (16, 12);
insert into advertisements_categories(advertisement_id, category_id) values (17, 40);
insert into advertisements_categories(advertisement_id, category_id) values (18, 36);
insert into advertisements_categories(advertisement_id, category_id) values (19, 26);
insert into advertisements_categories(advertisement_id, category_id) values (20, 43);
insert into advertisements_categories(advertisement_id, category_id) values (21, 12);