insert into profiles(email, phone_number, residence) values ('email', '0623890342', 'Groeningen');
insert into users(username, password, profile_id) values ('pipje', '$2a$12$GcbQlWzYl6xf1DbXTipSzOe2qrDKLj.TRxgDIDQoizHJ8bJoBLjlW', 1);
insert into roles(role) values ('ROLE_USER'), ('ROLE_ADMIN');
insert into users_roles(user_id, role) values ('1', 'ROLE_USER');
insert into users_roles(user_id, role) values ('1', 'ROLE_ADMIN');
insert into categories(parent_id, title) values (null, 'Voertuigen');
insert into categories(parent_id, title) values (1, 'Auto''s en motoren');
insert into categories(parent_id, title) values (1, 'Andere voertuigen');
insert into categories(parent_id, title) values (1, 'Boten');
insert into categories(parent_id, title) values (null, 'Verzamelobjecten');
insert into categories(parent_id, title) values (5, 'Munten');
insert into categories(parent_id, title) values (5, 'Postzegels');
insert into categories(parent_id, title) values (5, 'Antiek');
insert into categories(parent_id, title) values (5, 'Kunst');
insert into categories(parent_id, title) values (null, 'Kleding en sport');
insert into categories(parent_id, title) values (10, 'Mannen kleding');
insert into categories(parent_id, title) values (10, 'Vrouwen kleding');
insert into categories(parent_id, title) values (10, 'Kinder kleding');
insert into categories(parent_id, title) values (10, 'Baby kleding');
insert into categories(parent_id, title) values (10, 'Accessoires');
insert into categories(parent_id, title) values (10, 'Juwelen');
insert into categories(parent_id, title) values (10, 'Reisbagage');
insert into categories(parent_id, title) values (10, 'Sportuitrusting');
insert into categories(parent_id, title) values (10, 'Visuitrusting');
insert into categories(parent_id, title) values (null, 'Electronica');
insert into categories(parent_id, title) values (20, 'Computers');
insert into categories(parent_id, title) values (20, 'Tablets');
insert into categories(parent_id, title) values (20, 'Laptops');
insert into categories(parent_id, title) values (20, 'Telefoons');
insert into categories(parent_id, title) values (20, 'Camera''s');
insert into categories(parent_id, title) values (20, 'Tv''s');
insert into categories(parent_id, title) values (20, 'Audioapparatuur');
insert into categories(parent_id, title) values (20, 'Koptelefoons');
insert into categories(parent_id, title) values (20, 'Vriezers');
insert into categories(parent_id, title) values (20, 'Koelkasten');
insert into categories(parent_id, title) values (null, 'Huis en tuin');
insert into categories(parent_id, title) values (31, 'Tuinapparatuur');
insert into categories(parent_id, title) values (31, 'Tuinmeubels');
insert into categories(parent_id, title) values (31, 'Binnenmeubels');
insert into categories(parent_id, title) values (31, 'Slaapproducten');
insert into categories(parent_id, title) values (31, 'Stofzuigers');
insert into categories(parent_id, title) values (31, 'Keukengerei');
insert into categories(parent_id, title) values (31, 'Lampen');
insert into categories(parent_id, title) values (null, 'Eigen tijd');
insert into categories(parent_id, title) values (39, 'Boeken');
insert into categories(parent_id, title) values (39, 'Muziekinstrumenten');
insert into categories(parent_id, title) values (39, 'CD''s');
insert into categories(parent_id, title) values (39, 'Vinyl');
insert into categories(parent_id, title) values (39, 'Games');
insert into categories(parent_id, title) values (39, 'DVD''s');
insert into categories(parent_id, title) values (39, 'blu-ray');
insert into categories(parent_id, title) values (null, 'Gezondheidsproducten');
insert into categories(parent_id, title) values (47, 'Parfum');
insert into categories(parent_id, title) values (47, 'Makeup');
insert into categories(parent_id, title) values (47, 'Huidverzorging');
insert into categories(parent_id, title) values (47, 'Haarstijlproducten');
insert into categories(parent_id, title) values (47, 'Scheerproducten');
insert into advertisements(user_id, title, description, price, image, details, state, date, has_to_go) values (1, 'titel', null, 50.0, '1.png', null, null, null,'checked');
insert into advertisements(user_id, title, description, price, image, details, state, date, has_to_go) values (1, 'andere titel', null, 100.0, '1.png', null, null, null,'checked');